export  const songData =[
    {  
      title:'Chinni-Chinni-Asha',
        url:'Chinni-Chinni-Asha(PaglaSongs).mp3',
        image:'https://tse4.mm.bing.net/th?id=OIP.VL4NZGckXIgwQDM10doMBwHaEK&pid=Api&P=0&h=180'
    },
    {  
      title:'ring',
        url:'https://assets.coderrocketfuel.com/pomodoro-times-up.mp3',
        image:'https://tse1.mm.bing.net/th?id=OIP.N_1sUrFZhMvs1RpVYmbjLAHaHa&pid=Api&P=0&h=180'
    },
    {  
      title:'Heeriye',
        url:'Heeriye(PaglaSongs).mp3',
        image:'https://tse4.explicit.bing.net/th?id=OIP.3GaFdEW0ZPBRP_tjjuvM2AHaHa&pid=Api&P=0&h=180'
    },
    {  
      title:'kabhi-shaam',
        url:'Kabhi-Shaam-Dhale(PaglaSongs).mp3',
        image:'https://tse2.mm.bing.net/th?id=OIP.ZZxmml31AayPIV65dgrJnAHaHa&pid=Api&P=0&h=180'
    },
  ]
